### ISSUE TITLE
Numero de Deputados não Corresponde ao Cabeçalho

### ISSUE THREAD

**Issue by uira** [redelivre/mapadademocracia#2]
O número se referencia aos deputados do plenário e não da Comissão

![captura de tela 2016-03-26 as 03 49 40](https://cloud.githubusercontent.com/assets/89998/14061167/50ec8cb2-f358-11e5-8f50-f0367a9ba320.png)

**Comment by lfagundes** [comment]
Me incomoda um pouco a coerência com o número de cima, que se refere ao total (o 50 deputados hoje).

**Comment by brunosmartin** [comment]
Eu acho que deveria mostrar todos, e não só da comissão!

**Comment by uira** [comment]
Galera, vamos fazer duas páginas.

Uma com os membros da comissão e outra com o plenário. OK?
